import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/navigation/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const thiccBoi = localFont({
  src: "./fonts/THICCCBOI-Regular.ttf",
  variable: "--font-thicc-reg",
});

const thiccBoiBold = localFont({
  src: "./fonts/THICCCBOI-Bold.ttf",
  variable: "--font-thicc-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${thiccBoi.variable} ${thiccBoiBold.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
